/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f411xx.h>
#include <stm32f411xx_gpio_driver.h>

/*int main(void)
{
     Loop forever
	for(;;);
}*/

/*int main(void)
{
	return 0;
}*/

void EXTI0_IRQHandler(void)
{
	GPIO_IRQHandling(0);
}
