/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define ADC_BASE_ADDR 			0x40012000UL
#define ADC_CR1_REG_OFFSET 		0x04
#define ADC_CR1_REG_ADDR		(ADC_BASE_ADDR + ADC_CR1_REG_OFFSET)

#define RCC_BASE_ADDRESS		0x40023800UL
#define APB2_ENR_REG_OFFSET		0x44
#define APB2_ENR_REG_BASE		(RCC_BASE_ADDRESS + APB2_ENR_REG_OFFSET)

int main(void)
{
	uint32_t *pApb2EnrReg = (uint32_t*) APB2_ENR_REG_BASE;
	uint32_t *pAdcCr1Reg = (uint32_t*) ADC_CR1_REG_ADDR;

	// Enable the clock for APB2
	*pApb2EnrReg |= ( 1 << 8);

	// Modify the ADC cr1 register
	*pAdcCr1Reg |= ( 1 << 8);
    /* Loop forever */
	for(;;);
}
